name: first-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make setup
        run: make setup
      - name: make test
        run: make test
      - name: make lint
        run: make lint